#!/usr/bin/env php
<?php
use WebServer\Server; 
use WebServer\Request;
use WebServer\Response;

require 'vendor/autoload.php';

// This is a simple HTTP server that will listen on port 8080 and return "Hello World!" for every request.
array_shift($argv);

if(empty($argv)) {
    $port = 80;
} else {
    $port = array_shift($argv);
}

$server = new Server('127.0.0.1', $port);

$server->listen(function(Request $request) {
    echo $request->method(). ' ' . $request->uri() . "\n";

    return new Response( '<pre>'.print_r( $request, true ).'</pre>' );
});